### ISSUE TITLE
Tiles not showing

### ISSUE THREAD

**Issue by pyromanci** [DRKV333/MechTransfer#1]
Placing down the transfer pipes makes the other items connected vanish. They are there, but the graphics for them do not show.

**Comment by DRKV333** [comment]
This is most likely caused by SpiritMod, though it could be something I'm missing. The issue happens, because the CoordinateHeights of all of the 1x1 TileObjects is changed from { 16 } to { 20 }. I haven't yet nailed down where this happens exactly.

**Comment by DRKV333** [comment]
Spirit mod v1.3.3.0 fixed the issue.
