### ISSUE TITLE
1.4.4 port

### ISSUE THREAD

**Issue by RealCltdj** [DRKV333/MechTransfer#11]
I was wondering if I could try to port the mod to 1.4.4. I have on a personal level attempted to just use tModPorter but it still leaves a lot of errors and other issues for porting. I would like to officially ask if I can try my hand at porting it to 1.4.4 with a branch on this repo and maybe help if anybody want to help me. If you don't want me to have a branch on this repo, then I would like to ask for your permission to just use my own public one.

**Comment by DRKV333** [comment]
Feel free to do whatever you'd like with the mod in your own fork. I appreciate the heads up, but there is really no need to ask for permission. I have already given you permission: https://github.com/DRKV333/MechTransfer/blob/master/LICENSE
